/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package returndepositschemeapp;
import java.util.ArrayList;
import java.time.LocalDate;
import returndepositschemeapp.Deposit;
import returndepositschemeapp.Deposit;
import returndepositschemeapp.DepositCsvManager;
import returndepositschemeapp.DepositCsvManager;
import returndepositschemeapp.DepositMachineLocatorGUI;
import returndepositschemeapp.DepositMachineLocatorGUI;
import returndepositschemeapp.DepositMenuFrame;
import returndepositschemeapp.DepositMenuFrame;
import returndepositschemeapp.FeedbackGUI;
import returndepositschemeapp.FeedbackGUI;
import returndepositschemeapp.HomepageGUI;
import returndepositschemeapp.HomepageGUI;
import returndepositschemeapp.ProfileGUI;
import returndepositschemeapp.ProfileGUI;
import returndepositschemeapp.UserDeposits;
import returndepositschemeapp.UserDeposits;
/**
 *
 * @author Seamus90
 */
public class DepositHistoryFrame extends javax.swing.JFrame {
    private UserDeposits usersDeposits;

    //This allows all the access of FindClosestMachine
    DepositLocationManager machineFinder = DepositLocationManager.getInstanceFCM();
    
    /**
     * Creates new form DepositHistoryFrame
     * gui that displays a users deposit history, can filter by date
     */
    public DepositHistoryFrame() {
        initComponents();
        // get current user
        User currentUser = UserManager.getCurrentUser();
        // store current users email
        String currentUserEmail = currentUser.getEmail();
        
        // create depositcvsmanager instance
        DepositCsvManager depositCsvManager = new DepositCsvManager();
        
        // get users deposits from csv
        ArrayList<Deposit> userDepositsList = depositCsvManager.readUserDeposits(currentUserEmail);
        
        // initialise userdeposits
        this.usersDeposits = new UserDeposits(currentUserEmail, userDepositsList);
        
        // Print the user deposits to the JTextArea
        printUserDepositsToJTextArea();
    }
    
    // diplay user deposits in text area
    public void printUserDepositsToJTextArea() {
        // clear text area
        depositHistoryTextArea.setText("");
        
        // call method to get the output you want displayed
        String textToBeDisplayed = usersDeposits.getAllDepositDetails();
        // pass text to be displayed into the text area
        depositHistoryTextArea.setText(textToBeDisplayed);
        
        // displaying text area from the top
        depositHistoryTextArea.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entEirLbl = new javax.swing.JLabel();
        fromDateInputField = new javax.swing.JTextField();
        entEirLbl1 = new javax.swing.JLabel();
        toDateInputField = new javax.swing.JTextField();
        filterDateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        depositHistoryTextArea = new javax.swing.JTextArea();
        backToDepositMenuBtn = new javax.swing.JButton();
        resetFilterBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();
        depositBTN = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        entEirLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        entEirLbl.setForeground(new java.awt.Color(255, 255, 255));
        entEirLbl.setText("From Date:");

        entEirLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        entEirLbl1.setForeground(new java.awt.Color(255, 255, 255));
        entEirLbl1.setText("To Date: ");

        filterDateBtn.setBackground(new java.awt.Color(240, 240, 240));
        filterDateBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        filterDateBtn.setText("Filter");
        filterDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDateBtnActionPerformed(evt);
            }
        });

        depositHistoryTextArea.setColumns(20);
        depositHistoryTextArea.setRows(5);
        jScrollPane1.setViewportView(depositHistoryTextArea);

        backToDepositMenuBtn.setBackground(new java.awt.Color(240, 240, 240));
        backToDepositMenuBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        backToDepositMenuBtn.setText("Back");
        backToDepositMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDepositMenuBtnActionPerformed(evt);
            }
        });

        resetFilterBtn.setBackground(new java.awt.Color(240, 240, 240));
        resetFilterBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resetFilterBtn.setText("Reset");
        resetFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFilterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(entEirLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fromDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(entEirLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(filterDateBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(backToDepositMenuBtn)
                        .addGap(33, 33, 33)
                        .addComponent(resetFilterBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entEirLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entEirLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterDateBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToDepositMenuBtn)
                    .addComponent(resetFilterBtn))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        homeBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("Homepage");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        feedbackBtn.setBackground(new java.awt.Color(51, 51, 51));
        feedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feedbackBtn.setForeground(new java.awt.Color(255, 255, 255));
        feedbackBtn.setText("Feedback");
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });

        depositBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositBTN.setText("Deposit");
        depositBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBTNActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Machine Locator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        profileBtn.setBackground(new java.awt.Color(51, 51, 51));
        profileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(feedbackBtn)
                    .addComponent(depositBTN)
                    .addComponent(jButton1)
                    .addComponent(profileBtn))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        //Setting hompeage visible
        HomepageGUI home = new HomepageGUI();
        home.setVisible(true);
        
        //Collapsing current form
        setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        //Setting Feedback visible
        FeedbackGUI feedback = new FeedbackGUI();
        feedback.setVisible(true);
        
        //Collapsing current form
        setVisible(false);
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void depositBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBTNActionPerformed
        //Setting Deposit Frame visible
        DepositMenuFrame deposit = new DepositMenuFrame();
        deposit.setVisible(true);
        
        //Collapsing current form
        setVisible(false); 
    }//GEN-LAST:event_depositBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Setting DepositMachineLocator Gui visible
        DepositMachineLocatorGUI dmlg = new DepositMachineLocatorGUI(machineFinder);
        dmlg.setVisible(true);
        
        //Collapsing current form
        setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        //Setting the profile visible
        ProfileGUI profile = new ProfileGUI();
        profile.setVisible(true);
        
        //Collapsing current form
        setVisible(false); 
    }//GEN-LAST:event_profileBtnActionPerformed

    // takes user back to deposit menu
    private void backToDepositMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDepositMenuBtnActionPerformed
        // TODO add your handling code here:
        DepositMenuFrame depositMenu = new DepositMenuFrame();
        depositMenu.setVisible(true);
        // collapse current form
        setVisible(false);
    }//GEN-LAST:event_backToDepositMenuBtnActionPerformed

    // used to filter text area by dates 
    private void filterDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDateBtnActionPerformed
        // TODO add your handling code here:
        // get date input from fields
        String fromDateString = fromDateInputField.getText();
        String toDateString = toDateInputField.getText();
        
        // holds the result of filtered data
        String output;
        // if both contain dates
        if (fromDateString.isEmpty() == false && toDateString.isEmpty() == false) {
            LocalDate fromDate = LocalDate.parse(fromDateString);
            LocalDate toDate = LocalDate.parse(toDateString);
            output = usersDeposits.getDepositDetailsFilterBoth(fromDate, toDate);
        }else if (fromDateString.isEmpty() == false) {
            // if only the from date has an input
            LocalDate fromDate = LocalDate.parse(fromDateString);
            output = usersDeposits.getDepositDetailsFilterFromDate(fromDate);
        }else if (toDateString.isEmpty() == false) {
            // if only the to date has an input
            LocalDate toDate = LocalDate.parse(toDateString);
            output = usersDeposits.getDepositDetailsFilterToDate(toDate);
        }else {
            output = usersDeposits.getAllDepositDetails();
        }
        
        // clear input fields
        fromDateInputField.setText("");
        toDateInputField.setText("");

        // if the output equals this text or the output is empty, then it means that the search didnt find anything
        if (output.equals("***You have not made any deposits yet***") || output.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "No results found!");
            // reset deposit history details
            depositHistoryTextArea.setText(usersDeposits.getAllDepositDetails());
        } else {
            depositHistoryTextArea.setText(output);
        }
        depositHistoryTextArea.setCaretPosition(0);
    }//GEN-LAST:event_filterDateBtnActionPerformed

    // resets the text that appears the text area
    private void resetFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFilterBtnActionPerformed
        // TODO add your handling code here:
        fromDateInputField.setText("");
        toDateInputField.setText("");
        depositHistoryTextArea.setText(usersDeposits.getAllDepositDetails());
        
    }//GEN-LAST:event_resetFilterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToDepositMenuBtn;
    private javax.swing.JButton depositBTN;
    private javax.swing.JTextArea depositHistoryTextArea;
    private javax.swing.JLabel entEirLbl;
    private javax.swing.JLabel entEirLbl1;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JButton filterDateBtn;
    private javax.swing.JTextField fromDateInputField;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton resetFilterBtn;
    private javax.swing.JTextField toDateInputField;
    // End of variables declaration//GEN-END:variables
}
